### ISSUE TITLE
Block hash is longer that it should be on oasisscan.com

### ISSUE THREAD

**Issue by valentinbud** [bitcat365/oasisscan-backend#1]
The block hash on oasisscan.com is wrong on both `mainnet` and `testnet`. Please see below
<img width="1680" alt="Screenshot 2021-12-02 at 09 05 48" src="https://user-images.githubusercontent.com/3338528/144374324-07aed946-8624-44e9-a95e-229699886370.png">
<img width="1680" alt="Screenshot 2021-12-02 at 09 07 19" src="https://user-images.githubusercontent.com/3338528/144374470-0250e9f4-b387-44a4-88ba-2732e295acbc.png">

A correct hash looks like the following
<img width="1673" alt="Screenshot 2021-12-02 at 09 08 16" src="https://user-images.githubusercontent.com/3338528/144374622-870aceeb-e4c8-424b-b469-ce20d71d99b1.png">

Notice the difference in length. This issue misleads node operators when trying to use state sync.
See https://github.com/oasisprotocol/oasis-core/issues/4384 issue. Thanks.

**Comment by romever** [comment]
Thank you very much for raising this question, I have already fixed it.
