### ISSUE TITLE
Extend ChainTransactionInfoResponse object definition

### ISSUE THREAD

**Issue by buberdds** [bitcat365/oasisscan-backend#11]
Would it be possible to represent `ChainTransactionInfoResponse` `method`  https://github.com/bitcat365/oasisscan-backend/blob/master/api/api.json#L1983 as `ChainMethodsResponse` in `chain/methods` as `enum` instead of `string` ?

 ```
      "method": {
        "type": "string",
        "enum": [
          "staking.Transfer",
          "staking.AddEscrow"
          ...whatever Oasis Scan can have here 
        ]
      }
 ```

**Comment by romever** [comment]
I think the returned result list here is likely to change,not what I defined,which doesn't quite align with an enum type.
