### ISSUE TITLE
Address format diff between v1 and v2

### ISSUE THREAD

**Issue by buberdds** [bitcat365/oasisscan-backend#13]
Hi, did not check all runtime tx methods, but for `consensus.Withdraw` `ctx.from` address is now returned in `oasis1` not in `eth` format. Is this expected?

v1
https://api.oasisscan.com/mainnet/runtime/transaction/info?id=000000000000000000000000000000000000000000000000e2eaa99fc008f87f&hash=93952e9208d2c84ece6762591bb932f93427979189e5f07c7d0d290c672bf2bf

v2
https://api.oasisscan.com/v2/mainnet/runtime/transaction/info?id=000000000000000000000000000000000000000000000000e2eaa99fc008f87f&round=12638152&hash=93952e9208d2c84ece6762591bb932f93427979189e5f07c7d0d290c672bf2bf

**Comment by romever** [comment]
Yes, currently both addresses in `ctx `are in consensus format. Do you need to use evm addresses?

**Comment by buberdds** [comment]
Yes, I believe it would be much better. Showing oasis1 addr in this case might be misleading for end users and cause UX issues ( some users might attempt to transfer funds to that address).
