### ISSUE TITLE
ParaTime transactions appear to be no longer indexed

### ISSUE THREAD

**Issue by tjanez** [bitcat365/oasisscan-backend#4]
I made a deposit from a consensus account into an Emerald ParaTime account:
![Screenshot from 2022-07-29 20-19-06](https://user-images.githubusercontent.com/2518544/181821809-f6295c3d-f975-4574-aa88-ce960d3c18f2.png)
![Screenshot from 2022-07-29 20-19-15](https://user-images.githubusercontent.com/2518544/181821828-4cf5493e-9962-484d-bbcb-9d5c2a9cef2e.png)
![Screenshot from 2022-07-29 20-19-46](https://user-images.githubusercontent.com/2518544/181821851-a0cfbdd0-0c6f-4b22-b964-7564dc396037.png)

Clicking on the "View transaction records through explorer" redirects to:
https://www.oasisscan.com/paratimes/transactions/031efeabaa315e5c7b4fea4b89585063af63960e8c7a123265e32cd96c761a4e?runtime=000000000000000000000000000000000000000000000000e2eaa99fc008f87f

which shows nothing:
![Screenshot from 2022-07-29 20-21-05](https://user-images.githubusercontent.com/2518544/181822112-7597fd7e-85b4-49c6-82d5-f5a3ebf1a3df.png)

The Oasis Scan account page:
https://www.oasisscan.com/accounts/detail/oasis1qqk86skatdsuhq8a5qcyt9s8pf37etjrfqsdce5p

It shows the consensus part of the deposit into Emerald:
- a `staking.Allow` txn
- a `roothash.ExecutorCommit` txn which shows the event from the chosen consensus account into the Emerald consensus account)

However, switching to the Paratime tab in the Transactions panel doesn't show anything for this txn:
![Screenshot from 2022-07-29 20-30-51](https://user-images.githubusercontent.com/2518544/181822577-97da66b1-3a45-4be0-8c5a-a92213a816e8.png)

**Comment by wjdfx** [comment]
Thanks for report. oasis-node has a config mistake. has been solved.
