### ISSUE TITLE
API v2 swagger spec adjustment

### ISSUE THREAD

**Issue by buberdds** [bitcat365/oasisscan-backend#7]
Hey,

looks like there is a definition mismatch in swagger spec:
https://api.oasisscan.com/v2/swagger/api.json
https://github.com/bitcat365/oasisscan-backend/blob/master/api/api.json#L1542
`mapstringAccountRewardStatsInfo` -> `AccountRewardStatsInfo`

**Comment by romever** [comment]
Thanks for your feedback, you are right.I have just fixed this error.
