### ISSUE TITLE
Not able fetch runtime transactions

### ISSUE THREAD

**Issue by buberdds** [bitcat365/oasisscan-backend#8]
Hey,

in V1  `/chain/transactions` includes runtime txs associated with Consensus account via `runtime` query param 
`https://api.oasisscan.com/mainnet/swagger-ui/#/chain-controller/latestTransactionsUsingGET`.
This allows to fetch transactions methods like `consensus.Withdraw` etc and list deposits or withdraws in Wallet.

In V2 it is not possible. Is there a plan do migrate this query param to V2 or provide some other API for such case?

**Comment by romever** [comment]
Yes, I will plan to add the same way in V2 soon.Still using query param.

**Comment by buberdds** [comment]
I can see in Swagger that query param was added. thank you :saluting_face:
