### ISSUE TITLE
ValidatorInfo spec vs API response

### ISSUE THREAD

**Issue by buberdds** [bitcat365/oasisscan-backend#9]
Hey again,

in V2, API endpoint `validator/list` returns a list of `ValidatorInfo`. There are props that are defined as an `array`, but API returns `null`.
This may cause unexpected behaviors in clients if code is auto generated based on spec.

API: https://api.oasisscan.com/v2/mainnet/validator/list?orderBy=escrow&sort=desc
Spec: https://github.com/bitcat365/oasisscan-backend/blob/master/api/api.json#L3512
Problematic `ValidatorInfo` props: 
```
        "rates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Rate"
          }
        },
        "bounds": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Bound"
          }
        "runtimes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ValidatorRuntime"
          }
        },
```

1) Can we expect these props will have always values? (maybe it's indexing issue and data is not available yet?)
2) Can these array props default to an empty array?
3) Can spec be in openapi v3 to get nullable support?

**Comment by romever** [comment]
I would consider returning an empty array instead of null for array type properties.

**Comment by romever** [comment]
Since these fields do not need to be returned in the validator list, they are set to omitempty.

**Comment by buberdds** [comment]
works great, thank you :saluting_face:
